### PR TITLE
Mention UI tests in the testing section

### PR DESCRIPTION
**Pull request by arturs105**

### CODE REVIEW

**Comment by amulware** [comment]
This is app specific, should it be in our general guidelines?

**Comment by arturs105** [comment]
Our UI tests are not platform specific and the release testing issue template is not platform specific, so i think this section fits well here.

**Comment by kornelijepetak** [comment]
However, @amulware's comment does make sense tho. Which I think you might have misunderstood, @arturs105.

What he wanted to say is that `release-flow.md` explains the regular procedure for releasing our apps (current, and potentially future ones). However, your addition in this PR is dealing with Toggl App in particular. What he meant (at least from what I can fathom) is that this belongs to Toggl App docs (somewhere), not in generic procedure. 

Maybe we'll have some other app for which no UI tests will be made, in case of which, the addition to docs in this PR would be invalid.

I am revoking my approval until @amulware approves to add this addition here.

**Comment by amulware** [comment]
That is what I meant, yes.

**Comment by kornelijepetak** [comment]
What's up with this PR? It's somewhat stale, isn't it 😄

**Comment by amulware** [comment]
As such, I'm making an executive decision. 🕴

**Pull request closed without merging**
